server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crabfood
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  jwtSecret: "crabfoodSecretKey1234567890abcdefghijklmnopqrstuvwxyz"
  jwtExpirationMs: 86400000 # 24 hours

logging:
  level:
    org.springframework.security: DEBUG
    com.example.crabfood_api: DEBUG